### ISSUE TITLE
Default route is touched by romana

### ISSUE THREAD

**Issue by dng-dev** [romana/vpc-router#49]
I currently migrated from AWS Nat Gateways to an Nat Instance. After a few moments the default route over the instance 0.0.0.0/0 gets removed by romana. After switching back to Nat Gateways everything was working again.

**Comment by jbrendel** [comment]
Yes, I think I know why this may happen. Currently, Romana takes controls over all routes to instances, adds the ones it needs and removes those that it doesn't. At that point, I imagine, the default route to the NAT instance was removed.

I'll think of something and will keep you posted.
